[build-system]
requires = [
    "jupyter_packaging~=0.10,<2",  
    "setuptools>=40.8.0",
    "wheel",
    "jupyterlab~=3.6.6",
    "jupyter_server",
    "notebook",
    "boto3",
    "singleton-decorator",
    "colorlog",
    "s3fs"
    ]
build-backend = "setuptools.build_meta"
