version: '3.7'

# Settings and configurations that are common for all containers
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-29T01-40-52Z
    command: server --console-address ":9001"  /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/data

  jupyter:
    image: aristidetm/labextension-dev
    volumes:
      - ..:/workspace
    working_dir: /workspace
    ports:
      - 8888:8888
      - 9999:9999
    command: sleep infinity
    depends_on:
      - minio

volumes:
  data: